# Generated by Django 3.2 on 2021-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('autoescuela_id', models.CharField(max_length=10, verbose_name='Código Autoescuela')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Autoescuela')),
                ('seccion', models.IntegerField(verbose_name='Código Sección')),
                ('permiso', models.CharField(max_length=10, verbose_name='Tipo Permiso')),
                ('examen', models.CharField(max_length=50, verbose_name='Tipo Examen')),
                ('aptos', models.IntegerField(verbose_name='Número Aptos')),
                ('aptos_1', models.IntegerField(verbose_name='Número Aptos 1ª convocatoria')),
                ('no_aptos', models.IntegerField(verbose_name='Número Suspendidos')),
                ('total', models.IntegerField(verbose_name='Total Examenados')),
                ('year', models.IntegerField(verbose_name='Año')),
            ],
        ),
    ]
