# Generated by Django 3.2 on 2021-05-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoescuela_id', models.CharField(max_length=10, verbose_name='Código Autoescuela')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Autoescuela')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField(verbose_name='Código Sección')),
                ('permiso', models.CharField(max_length=10, verbose_name='Tipo Permiso')),
                ('examen', models.CharField(max_length=50, verbose_name='Tipo Examen')),
                ('aptos', models.IntegerField(verbose_name='Número Aptos')),
                ('aptos_1', models.IntegerField(verbose_name='Número Aptos 1ª convocatoria')),
                ('no_aptos', models.IntegerField(verbose_name='Número Suspendidos')),
                ('total', models.IntegerField(verbose_name='Total Examenados')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.schools')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
            },
        ),
    ]
